package model;
// Generated Jan 1, 2017 5:35:08 PM by Hibernate Tools 4.3.1



/**
 * Member generated by hbm2java
 */
public class Member  implements java.io.Serializable {


     private Integer id;
     private String name;
     private String address;
     private String email;
     private String phone;
     private String nid;
     private String statues;

    public Member() {
    }

    public Member(String name, String address, String email, String phone, String nid, String statues) {
       this.name = name;
       this.address = address;
       this.email = email;
       this.phone = phone;
       this.nid = nid;
       this.statues = statues;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }
    public String getNid() {
        return this.nid;
    }
    
    public void setNid(String nid) {
        this.nid = nid;
    }
    public String getStatues() {
        return this.statues;
    }
    
    public void setStatues(String statues) {
        this.statues = statues;
    }




}


