package model;
// Generated Jan 1, 2017 5:35:08 PM by Hibernate Tools 4.3.1



/**
 * Reservation generated by hbm2java
 */
public class Reservation  implements java.io.Serializable {


     private Integer id;
     private String name;
     private String address;
     private String email;
     private String phone;
     private String bookingDate;
     private String checkOutDate;
     private String dayCount;
     private String roomNo;
     private String roomCount;
     private String bel;
     private String statues;

    public Reservation() {
    }

    public Reservation(String name, String address, String email, String phone, String bookingDate, String checkOutDate, String dayCount, String roomNo, String roomCount, String bel, String statues) {
       this.name = name;
       this.address = address;
       this.email = email;
       this.phone = phone;
       this.bookingDate = bookingDate;
       this.checkOutDate = checkOutDate;
       this.dayCount = dayCount;
       this.roomNo = roomNo;
       this.roomCount = roomCount;
       this.bel = bel;
       this.statues = statues;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }
    public String getBookingDate() {
        return this.bookingDate;
    }
    
    public void setBookingDate(String bookingDate) {
        this.bookingDate = bookingDate;
    }
    public String getCheckOutDate() {
        return this.checkOutDate;
    }
    
    public void setCheckOutDate(String checkOutDate) {
        this.checkOutDate = checkOutDate;
    }
    public String getDayCount() {
        return this.dayCount;
    }
    
    public void setDayCount(String dayCount) {
        this.dayCount = dayCount;
    }
    public String getRoomNo() {
        return this.roomNo;
    }
    
    public void setRoomNo(String roomNo) {
        this.roomNo = roomNo;
    }
    public String getRoomCount() {
        return this.roomCount;
    }
    
    public void setRoomCount(String roomCount) {
        this.roomCount = roomCount;
    }
    public String getBel() {
        return this.bel;
    }
    
    public void setBel(String bel) {
        this.bel = bel;
    }
    public String getStatues() {
        return this.statues;
    }
    
    public void setStatues(String statues) {
        this.statues = statues;
    }




}


