package model;
// Generated Jan 1, 2017 5:35:08 PM by Hibernate Tools 4.3.1



/**
 * Room generated by hbm2java
 */
public class Room  implements java.io.Serializable {


     private Integer id;
     private String roomNo;
     private String statues;

    public Room() {
    }

    public Room(String roomNo, String statues) {
       this.roomNo = roomNo;
       this.statues = statues;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getRoomNo() {
        return this.roomNo;
    }
    
    public void setRoomNo(String roomNo) {
        this.roomNo = roomNo;
    }
    public String getStatues() {
        return this.statues;
    }
    
    public void setStatues(String statues) {
        this.statues = statues;
    }




}


